name: Update Subscription

on:
  schedule:
    - cron: "*/10 * * * *"   # اجرای خودکار هر ۱۰ دقیقه (بر اساس UTC)
  workflow_dispatch:         # امکان اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt

      - run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output.txt index.html
          git commit -m "Auto update subscription" || echo "No changes to commit"
          git pull --rebase
          git push
